### ISSUE TITLE
Better Stack Traces

### ISSUE THREAD

**Issue by kilianc** [request/promise-core#5]
At the moment awaiting a request-promise call will throw an error with this stack trace:

![](https://www.dropbox.com/s/w3fhbvzx22t8j3z/Screenshot%202017-07-31%2011.43.45.png?dl=1)

This leaves me completely blind of what's failing and where. Is there a way to have better stack traces that I am not aware of?

**Comment by analog-nico** [comment]
You may google for “long stack traces node”.

**Comment by brandonros** [comment]
Why does `request-promise-core` lose the original function that calls it?

```
StatusCodeError: 500 - "Internal error"
    at new StatusCodeError (/app/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/app/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/app/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (/app/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

I feel like if the `request-promise-core` code looked like this:

```
const rp = {
  get: () => {
    return new Promise((resolve, reject) => {
      let data = ''
      http.get(uri, (res) => {
        data += chunk
      })
      resp.on(() => {
        if (res.status >= 400) {
          reject(new Error('Bad status'))
        } else {
          resolve(data)
        }
      })
    })
  }
}

await rp.get(options)
```

You wouldn't need long stack traces. Why wasn't the code written in a fashion that retains the original calling function for stack traces?
